spring.application.name=OgrenciSosyalPlatformu

# --- H2 VERİTABANI AYARLARI (GÜNCELLENDİ - KESİN ÇÖZÜM) ---
# Sorunlu parametreleri kaldırdık. Sadece dosya yolunu belirtiyoruz.
spring.datasource.url=jdbc:h2:file:./data/sosyaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Konsolunu Aktif Et
spring.h2.console.enabled=true

# Tabloları koru (Uygulama kapanınca silinmesin)
spring.jpa.hibernate.ddl-auto=update

# --- DOSYA YÜKLEME AYARLARI (50MB) ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# --- LOG AYARLARI ---
logging.level.org.springframework.web=INFO